version: '3.1'

services:
  db:
    container_name: '${PROJECT_NAME}-MYSQL'    
    platform: linux/x86_64
    image: mysql:8.0.28
    ports:
      - 3308:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: '${DATABASE_NAME}'
      MYSQL_ROOT_PASSWORD: '${DATABASE_PASS}'